#!/usr/bin/env python3
"""
Generates firms.yaml from a seed list.

Seed tuple: (name, category, regions, ats_hints, extra_slugs)
  category: prop | fund | bank | exchange | fintech | crypto | vendor
  regions:  comma string of ISO-ish region tags, informational only
  ats_hints: list like ["greenhouse:janestreet"] - probed FIRST, but never trusted blindly
  extra_slugs: additional slug candidates to try if hints miss

Run:  python build_registry.py > firms.yaml
"""
import re
import sys

import yaml

# --------------------------------------------------------------------------
# MARKET MAKERS / PROPRIETARY TRADING
# --------------------------------------------------------------------------
PROP = [
    ("Jane Street", "us,uk,hk,sg,nl", ["html:https://www.janestreet.com/join-jane-street/open-roles/"], ["janestreet", "jane-street"]),
    ("Citadel Securities", "us,uk,hk,sg,ie", ["html:https://www.citadelsecurities.com/careers/open-opportunities/"], ["citadelsecurities"]),
    ("Optiver", "nl,us,au,uk,sg,hk,tw,in", ["html:https://optiver.com/working-at-optiver/career-opportunities/"], ["optiver", "optiverus"]),
    ("IMC Trading", "nl,us,au,in,ch", ["html:https://careers.imc.com/us/en/search-results"], ["imc", "imctrading", "imc-trading"]),
    ("Susquehanna International Group", "us,ie,au,nl,jp,hk,sg", ["html:https://careers.sig.com/search-jobs"], ["sig", "susquehanna"]),
    ("Jump Trading", "us,uk,sg,hk,nl", ["greenhouse:jumptrading"], ["jumptrading", "jump"]),
    ("Hudson River Trading", "us,uk,sg,ie,au", ["greenhouse:hrttalentcommunity", "html:https://www.hudsonrivertrading.com/careers/"], ["hudsonrivertrading", "hrt", "wearehrt"]),
    ("DRW", "us,uk,nl,sg,ca", ["greenhouse:drweng"], ["drw", "drwtrading", "drweng"]),
    ("Tower Research Capital", "us,uk,sg,in,hk", ["greenhouse:towerresearchcapital"], ["tower", "towerresearch"]),
    ("Flow Traders", "nl,us,sg,hk,uk", ["greenhouse:flowtraders"], ["flowtraders", "flow-traders"]),
    ("XTX Markets", "uk,sg,us,in", ["greenhouse:xtxmarkets"], ["xtx", "xtxmarkets"]),
    ("Virtu Financial", "us,ie,sg,au", ["greenhouse:virtufinancial"], ["virtu", "virtufinancial"]),
    ("Akuna Capital", "us,au,cn,uk", ["greenhouse:akunacapital"], ["akuna", "akunacapital"]),
    ("Old Mission Capital", "us,uk", ["greenhouse:oldmissioncapital"], ["oldmission", "oldmissioncapital"]),
    ("Wolverine Trading", "us", [], ["wolverine", "wolverinetrading"]),
    ("Belvedere Trading", "us", [], ["belvedere", "belvederetrading"]),
    ("PEAK6", "us,ie,in", ["greenhouse:peak6"], ["peak6"]),
    ("Chicago Trading Company", "us", ["greenhouse:chicagotradingcompany"], ["ctc", "chicagotrading"]),
    ("Group One Trading", "us", [], ["grouponetrading", "group1trading"]),
    ("Five Rings", "us,in", ["greenhouse:fiverings"], ["fiverings", "fiveringsllc"]),
    ("Headlands Technologies", "us,uk,sg", ["greenhouse:headlandstech"], ["headlands", "headlandstech"]),
    ("Radix Trading", "us,uk", ["lever:radix"], ["radix", "radixtrading"]),
    ("Vatic Labs", "us,uk", ["greenhouse:vaticlabs"], ["vatic", "vaticlabs"]),
    ("Quantlab Financial", "us,uk,sg", ["greenhouse:quantlab"], ["quantlab", "quantlabfinancial"]),
    ("TransMarket Group", "us,uk,sg", [], ["transmarket", "transmarketgroup"]),
    ("Allston Trading", "us", [], ["allston", "allstontrading"]),
    ("Teza Technologies", "us", [], ["teza", "tezatech"]),
    ("Tradebot Systems", "us", [], ["tradebot", "tradebotsystems"]),
    ("Geneva Trading", "us,ie", ["greenhouse:genevatrading"], ["genevatrading"]),
    ("Eagle Seven", "us", [], ["eagleseven", "eagle7"]),
    ("Marquette Partners", "us", [], ["marquettepartners"]),
    ("Simplex Trading", "us", [], ["simplextrading"]),
    ("XR Trading", "us", [], ["xrtrading"]),
    ("Volant Trading", "us", [], ["volanttrading", "volant"]),
    ("Maven Securities", "uk,hk,sg,us", ["greenhouse:mavensecurities"], ["maven", "mavensecurities"]),
    ("Da Vinci Trading", "nl", ["html:https://davinciderivatives.com/careers/"], ["davincitrading", "davinciderivatives"]),
    ("All Options", "nl,us", [], ["alloptions"]),
    ("Webb Traders", "nl", [], ["webbtraders"]),
    ("Amsterdam Trading Group", "nl", [], ["amsterdamtradinggroup", "atg"]),
    ("Mako Trading", "uk,sg", [], ["makotrading", "makoglobal"]),
    ("Liquid Capital", "uk,au,hk", [], ["liquidcapital", "liquidcapitalgroup"]),
    ("OSTC", "uk,pl,in", [], ["ostc", "ostcltd"]),
    ("Cutler Group", "us", [], ["cutlergroup"]),
    ("Hehmeyer", "us,uk", [], ["hehmeyer"]),
    ("Valkyrie Trading", "us", [], ["valkyrietrading"]),
    ("Gelber Group", "us", [], ["gelbergroup", "gelber"]),
    ("Kershner Trading Group", "us", [], ["kershnertrading", "kershner"]),
    ("Seven Points Capital", "us", [], ["sevenpointscapital"]),
    ("GTS", "us", ["greenhouse:gtsx"], ["gts", "gtsx"]),
    ("Hap Capital", "us", [], ["hapcapital"]),
    ("Spot Trading", "us", [], ["spottrading"]),
    ("Prime Trading", "us", [], ["primetrading"]),
    ("Tibra Capital", "au,uk", [], ["tibra", "tibracapital"]),
    ("Vivienne Court Trading", "au", [], ["viviennecourt", "vivcourt"]),
    ("Eclipse Options", "au", [], ["eclipseoptions"]),
    ("Grasshopper Asia", "sg", [], ["grasshopper", "grasshopperasia"]),
    ("Graviton Research Capital", "in", [], ["graviton", "gravitontrading"]),
    ("AlphaGrep Securities", "in,sg", [], ["alphagrep"]),
    ("Quadeye Securities", "in", [], ["quadeye"]),
    ("iRage Capital", "in", [], ["irage", "iragecapital"]),
    ("NK Securities Research", "in", [], ["nksecurities", "nkrsec"]),
    ("Futures First", "in", [], ["futuresfirst"]),
    ("Estee Advisors", "in", [], ["estee", "esteeadvisors"]),
    ("Dolat Capital", "in", [], ["dolatcapital"]),
    ("QuantBox Research", "in", [], ["quantbox"]),
    ("Open Futures", "in", [], ["openfutures"]),
    ("Aquatic Capital Management", "us", ["greenhouse:aquatic"], ["aquatic", "aquaticcapital"]),
    ("Talos Trading", "us", [], ["talostrading"]),
    ("Matrix Executions", "us", [], ["matrixexecutions"]),
    ("T3 Trading Group", "us", [], ["t3trading"]),
    ("SMB Capital", "us", [], ["smbcapital", "smbtraining"]),
    ("Bluefin Companies", "us", [], ["bluefincompanies", "bluefin"]),
    ("Consolidated Trading", "us", [], ["consolidatedtrading"]),
    ("Jane Capital Partners", "us", [], ["janecapital"]),
    ("Sumo Capital", "us", [], ["sumocapital"]),
    ("Optimal Trading", "us", [], ["optimaltrading"]),
    ("Nine Mile Financial", "au", [], ["ninemilefinancial"]),
    ("Zeta Markets", "au", [], ["zetamarkets"]),
    ("Susquehanna Pacific", "au", [], ["susquehannapacific"]),
]

# --------------------------------------------------------------------------
# HEDGE FUNDS / QUANT ASSET MANAGERS
# --------------------------------------------------------------------------
FUND = [
    ("Citadel", "us,uk,hk,sg,ie", ["html:https://www.citadel.com/careers/open-opportunities/"], ["citadel", "citadelllc"]),
    ("Millennium Management", "us,uk,sg,hk,il", ["greenhouse:millennium"], ["millennium", "mlp", "millenniummanagement"]),
    ("Point72", "us,uk,sg,hk,jp", ["greenhouse:point72"], ["point72", "point72assetmanagement"]),
    ("Balyasny Asset Management", "us,uk,hk,sg", ["greenhouse:balyasny"], ["balyasny", "bamfunds"]),
    ("ExodusPoint Capital", "us,uk,sg,hk", ["greenhouse:exoduspoint"], ["exoduspoint"]),
    ("Schonfeld Strategic Advisors", "us,uk,sg,hk", ["greenhouse:schonfeld"], ["schonfeld"]),
    ("Verition Fund Management", "us,uk,sg", ["greenhouse:verition"], ["verition"]),
    ("Walleye Capital", "us,uk,sg", ["greenhouse:walleyecapital"], ["walleye", "walleyecapital"]),
    ("Squarepoint Capital", "us,uk,fr,sg,hk,in", ["greenhouse:squarepointcapital"], ["squarepoint", "squarepointcapital"]),
    ("Qube Research & Technologies", "uk,us,sg,hk,in", ["greenhouse:qube"], ["qube", "quberesearch", "qrt"]),
    ("Man Group", "uk,us,ch,hk,sg", ["workday:mangroup"], ["mangroup", "manahl", "man"]),
    ("Two Sigma", "us,uk,jp,hk", ["greenhouse:twosigma"], ["twosigma", "two-sigma"]),
    ("D. E. Shaw & Co.", "us,uk,in,hk", ["html:https://www.deshaw.com/careers"], ["deshaw", "deshawgroup"]),
    ("Renaissance Technologies", "us", [], ["renaissancetechnologies", "rentec"]),
    ("AQR Capital Management", "us,uk,de,au", ["greenhouse:aqrcapitalmanagement"], ["aqr", "aqrcapital"]),
    ("Bridgewater Associates", "us,sg", ["greenhouse:bridgewater"], ["bridgewater", "bridgewaterassociates"]),
    ("PDT Partners", "us", ["greenhouse:pdtpartners"], ["pdtpartners", "pdt"]),
    ("The Voleon Group", "us", ["greenhouse:voleon"], ["voleon", "voleongroup"]),
    ("Marshall Wace", "uk,us,hk,sg", ["greenhouse:marshallwace"], ["marshallwace"]),
    ("Brevan Howard", "uk,us,ch,sg,ae,il", ["greenhouse:brevanhoward"], ["brevanhoward"]),
    ("Rokos Capital Management", "uk,us,sg", ["greenhouse:rokoscapital"], ["rokos", "rokoscapital"]),
    ("Capula Investment Management", "uk,us,jp,sg", [], ["capula", "capulaglobal"]),
    ("Eisler Capital", "uk,us,sg", ["greenhouse:eislercapital"], ["eisler", "eislercapital"]),
    ("Winton", "uk,us,hk,au", [], ["winton", "wintoncapital"]),
    ("GSA Capital", "uk,us", [], ["gsacapital", "gsa"]),
    ("Aspect Capital", "uk,us", [], ["aspectcapital", "aspect"]),
    ("Systematica Investments", "ch,uk,us,sg", [], ["systematica", "systematicainvestments"]),
    ("Florin Court Capital", "uk", [], ["florincourt"]),
    ("Quadrature Capital", "uk", ["greenhouse:quadraturecapital"], ["quadrature", "quadraturecapital"]),
    ("G-Research", "uk,us,ch,tr", ["html:https://www.gresearch.com/careers/"], ["gresearch", "g-research"]),
    ("Trium Capital", "uk", [], ["triumcapital"]),
    ("Cheyne Capital", "uk", [], ["cheynecapital"]),
    ("CQS", "uk,us,hk", [], ["cqs", "cqsm"]),
    ("Lansdowne Partners", "uk", [], ["lansdownepartners"]),
    ("Sculptor Capital Management", "us,uk,hk", [], ["sculptorcapital", "sculptor"]),
    ("Elliott Investment Management", "us,uk,hk", ["greenhouse:elliottmanagement"], ["elliott", "elliottmanagement"]),
    ("Davidson Kempner", "us,uk,hk", [], ["davidsonkempner", "dkpartners"]),
    ("King Street Capital", "us,uk,sg", [], ["kingstreet", "kingstreetcapital"]),
    ("Magnetar Capital", "us,uk", ["greenhouse:magnetar"], ["magnetar", "magnetarcapital"]),
    ("Garda Capital Partners", "us,ch", [], ["gardacapital", "garda"]),
    ("LMR Partners", "uk,us,hk,ae", [], ["lmrpartners", "lmr"]),
    ("Hudson Bay Capital", "us,uk", [], ["hudsonbaycapital"]),
    ("Alyeska Investment Group", "us", [], ["alyeska", "alyeskacapital"]),
    ("Holocene Advisors", "us", [], ["holoceneadvisors"]),
    ("Woodline Partners", "us", [], ["woodlinepartners"]),
    ("Candlestick Capital", "us", [], ["candlestickcapital"]),
    ("Freestone Grove Partners", "us", [], ["freestonegrove"]),
    ("Jain Global", "us,uk,hk,sg", ["greenhouse:jainglobal"], ["jainglobal", "jain"]),
    ("Bracebridge Capital", "us", [], ["bracebridgecapital"]),
    ("Arrowstreet Capital", "us", ["greenhouse:arrowstreetcapital"], ["arrowstreet", "arrowstreetcapital"]),
    ("Acadian Asset Management", "us,uk,au,sg,jp", [], ["acadian", "acadianasset"]),
    ("Dimensional Fund Advisors", "us,uk,au,sg", ["workday:dimensional"], ["dimensional", "dfa"]),
    ("Voloridge Investment Management", "us", ["greenhouse:voloridge"], ["voloridge"]),
    ("SurgoCap Partners", "us", [], ["surgocap"]),
    ("Taula Capital", "uk", [], ["taulacapital"]),
    ("Ilex Capital Partners", "uk", [], ["ilexcapital"]),
    ("Diameter Capital Partners", "us,uk", [], ["diametercapital"]),
    ("Silver Point Capital", "us", [], ["silverpointcapital"]),
    ("Marathon Asset Management", "us,uk", [], ["marathonassetmanagement"]),
    ("Fortress Investment Group", "us,uk,jp", [], ["fortress", "fortressinvestment"]),
    ("Cinctive Capital", "us", [], ["cinctivecapital"]),
    ("Tudor Investment Corporation", "us,uk,sg", [], ["tudor", "tudorinvestment"]),
    ("Moore Capital Management", "us,uk", [], ["moorecapital"]),
    ("Caxton Associates", "us,uk,sg", [], ["caxton", "caxtonassociates"]),
    ("Element Capital Management", "us", [], ["elementcapital"]),
    ("Autonomy Capital", "us,uk", [], ["autonomycapital"]),
    ("Alphadyne Asset Management", "us,uk,sg,hk", [], ["alphadyne"]),
    ("Kirkoswald Asset Management", "us,uk", [], ["kirkoswald"]),
    ("Symmetry Investments", "hk,uk,us,sg", [], ["symmetryinvestments"]),
    ("Modular Asset Management", "sg", [], ["modularasset"]),
    ("Dymon Asia Capital", "sg,hk", [], ["dymonasia", "dymon"]),
    ("Quantedge Capital", "sg,us", [], ["quantedge"]),
    ("Pinpoint Asset Management", "hk,cn", [], ["pinpointasset"]),
    ("Polymer Capital Management", "hk,sg", [], ["polymercapital"]),
    ("Triata Capital", "hk", [], ["triatacapital"]),
    ("FengHe Fund Management", "sg,hk", [], ["fenghefund"]),
    ("Aspex Management", "hk", [], ["aspexmanagement"]),
    ("Hillhouse Investment", "sg,hk,cn,us", [], ["hillhouse", "hillhousecapital"]),
    ("Myriad Asset Management", "hk", [], ["myriadasset"]),
    ("Tybourne Capital", "hk", [], ["tybournecapital"]),
    ("Oasis Management", "hk,jp", [], ["oasiscapital", "oasismanagement"]),
    ("Indus Capital Partners", "us,hk,jp", [], ["induscapital"]),
    ("Coatue Management", "us,uk,hk", ["greenhouse:coatue"], ["coatue"]),
    ("Tiger Global Management", "us", [], ["tigerglobal"]),
    ("Viking Global Investors", "us,uk,hk", [], ["vikingglobal"]),
    ("Lone Pine Capital", "us", [], ["lonepinecapital"]),
    ("Maverick Capital", "us", [], ["maverickcapital"]),
    ("Third Point", "us", [], ["thirdpoint", "thirdpointllc"]),
    ("Farallon Capital Management", "us,sg,hk", [], ["farallon", "faralloncapital"]),
    ("Angelo Gordon", "us,uk,hk", [], ["angelogordon"]),
    ("Anchorage Capital Group", "us,uk", [], ["anchoragecapital"]),
    ("Blue Owl Capital", "us,uk,hk", ["greenhouse:blueowlcapital"], ["blueowl", "blueowlcapital"]),
    ("Sixth Street", "us,uk,hk", ["greenhouse:sixthstreet"], ["sixthstreet"]),
    ("Blackstone", "us,uk,hk,sg,in", ["greenhouse:blackstone"], ["blackstone"]),
    ("KKR", "us,uk,hk,sg,jp", ["workday:kkr"], ["kkr"]),
    ("Apollo Global Management", "us,uk,hk,sg,in", ["workday:apollo"], ["apollo", "apolloglobal"]),
    ("The Carlyle Group", "us,uk,hk,sg,jp", ["workday:carlyle"], ["carlyle", "carlylegroup"]),
    ("Ares Management", "us,uk,hk,sg", ["workday:ares"], ["ares", "aresmgmt"]),
    ("TPG", "us,uk,hk,sg", ["greenhouse:tpg"], ["tpg", "tpginc"]),
    ("Brookfield Asset Management", "ca,us,uk,au,in", ["workday:brookfield"], ["brookfield"]),
    ("Oaktree Capital Management", "us,uk,hk,sg", ["workday:oaktree"], ["oaktree", "oaktreecapital"]),
    ("PIMCO", "us,uk,de,sg,hk,jp", ["workday:pimco"], ["pimco"]),
    ("BlackRock", "us,uk,de,sg,hk,in", ["workday:blackrock"], ["blackrock"]),
    ("Vanguard", "us,uk,au", ["workday:vanguard"], ["vanguard"]),
    ("State Street", "us,uk,ie,pl,in", ["workday:statestreet"], ["statestreet"]),
    ("Fidelity Investments", "us,ie,in", ["workday:fidelity"], ["fidelity", "fidelityinvestments"]),
    ("Fidelity International", "uk,cn,jp,in", [], ["fidelityinternational", "fil"]),
    ("Wellington Management", "us,uk,sg,hk,jp", ["workday:wellington"], ["wellington", "wellingtonmanagement"]),
    ("T. Rowe Price", "us,uk,hk,sg,jp", ["workday:troweprice"], ["troweprice", "trowe"]),
    ("Capital Group", "us,uk,sg,hk,in", ["workday:capitalgroup"], ["capitalgroup"]),
    ("Invesco", "us,uk,de,hk,sg,in", ["workday:invesco"], ["invesco"]),
    ("Janus Henderson", "us,uk,sg", ["workday:janushenderson"], ["janushenderson"]),
    ("Schroders", "uk,sg,hk,ch", ["workday:schroders"], ["schroders"]),
    ("Amundi", "fr,uk,it,sg", [], ["amundi"]),
    ("AXA Investment Managers", "fr,uk,de,jp", [], ["axaim", "axa"]),
    ("Legal & General Investment Management", "uk,us", [], ["lgim", "legalandgeneral"]),
    ("abrdn", "uk,sg,hk", [], ["abrdn", "aberdeen"]),
    ("Baillie Gifford", "uk,us", [], ["bailliegifford"]),
    ("Neuberger Berman", "us,uk,hk,jp", ["workday:neubergerberman"], ["neubergerberman"]),
    ("Nuveen", "us,uk", [], ["nuveen"]),
    ("MFS Investment Management", "us,uk,sg", [], ["mfs", "mfsinvestment"]),
    ("GMO", "us,uk,au,sg", [], ["gmo", "gmollc"]),
    ("Robeco", "nl,ch,hk", [], ["robeco"]),
    ("APG Asset Management", "nl,us,hk", [], ["apg", "apgassetmanagement"]),
    ("PGGM", "nl", [], ["pggm"]),
    ("Norges Bank Investment Management", "no,uk,us,sg", [], ["nbim", "norgesbank"]),
    ("GIC", "sg,uk,us", ["workday:gic"], ["gic"]),
    ("Temasek", "sg,us,uk,in,cn", [], ["temasek"]),
    ("CPP Investments", "ca,uk,us,hk,in", ["workday:cppib"], ["cppib", "cppinvestments"]),
    ("OMERS", "ca,uk,us", [], ["omers"]),
    ("Ontario Teachers' Pension Plan", "ca,uk,sg", [], ["otpp", "ontarioteachers"]),
    ("PSP Investments", "ca,uk", [], ["pspinvestments"]),
    ("CDPQ", "ca,us,sg", [], ["cdpq"]),
    ("Mubadala", "ae,us,uk", [], ["mubadala"]),
    ("ADIA", "ae", [], ["adia"]),
    ("PIF", "sa", [], ["pif", "publicinvestmentfund"]),
    ("QIA", "qa", [], ["qia", "qatarinvestmentauthority"]),
    ("Trexquant Investment", "us", [], ["trexquant"]),
    ("WorldQuant", "us,uk,sg,hk,in,vn,ru", ["greenhouse:worldquant"], ["worldquant"]),
    ("Numerai", "us", [], ["numerai"]),
    ("Laurion Capital Management", "us,uk,hk", [], ["laurioncapital"]),
    ("Cubist Systematic Strategies", "us,uk,hk", [], ["cubistsystematic", "cubist"]),
    ("Kadensa Capital", "hk", [], ["kadensacapital"]),
    ("Ovata Capital Management", "hk", [], ["ovatacapital"]),
    ("Segantii Capital Management", "hk", [], ["segantii"]),
    ("First Quadrant", "us", [], ["firstquadrant"]),
    ("Research Affiliates", "us", [], ["researchaffiliates"]),
    ("Los Angeles Capital Management", "us", [], ["lacapm", "losangelescapital"]),
    ("Martingale Asset Management", "us", [], ["martingale"]),
    ("Parametric Portfolio Associates", "us", [], ["parametric", "parametricportfolio"]),
]

# --------------------------------------------------------------------------
# BANKS (S&T, strats, quant, markets)
# --------------------------------------------------------------------------
BANK = [
    ("Goldman Sachs", "us,uk,in,sg,hk,jp,pl", ["html:https://higher.gs.com/roles"], ["goldmansachs", "gs"]),
    ("Morgan Stanley", "us,uk,in,hk,sg,jp,hu", ["workday:morganstanley"], ["morganstanley", "ms"]),
    ("JPMorgan Chase", "us,uk,in,sg,hk,pl", ["workday:jpmc"], ["jpmorgan", "jpmc", "jpmorganchase"]),
    ("Bank of America", "us,uk,in,sg,hk", ["workday:bankofamerica"], ["bankofamerica", "bofa", "baml"]),
    ("Citi", "us,uk,in,sg,hk,pl,ie", ["workday:citi"], ["citi", "citigroup"]),
    ("Barclays", "uk,us,in,sg,jp", ["workday:barclays"], ["barclays"]),
    ("HSBC", "uk,hk,in,sg,us,pl", ["workday:hsbc"], ["hsbc"]),
    ("Deutsche Bank", "de,uk,us,in,sg", ["workday:db"], ["deutschebank", "db"]),
    ("UBS", "ch,uk,us,sg,hk,pl,in", ["workday:ubs"], ["ubs"]),
    ("BNP Paribas", "fr,uk,us,in,sg,pt", ["html:https://group.bnpparibas/en/careers/job-offers"], ["bnpparibas", "bnp"]),
    ("Societe Generale", "fr,uk,us,in,hk", [], ["societegenerale", "socgen", "sg"]),
    ("Natixis", "fr,uk,us,pt", [], ["natixis"]),
    ("Credit Agricole CIB", "fr,uk,us,sg,hk", [], ["creditagricole", "ca-cib"]),
    ("Santander", "es,uk,us,pl,br", ["workday:santander"], ["santander"]),
    ("BBVA", "es,uk,us,mx", [], ["bbva"]),
    ("ING", "nl,be,uk,pl,sg", ["workday:ing"], ["ing", "inggroup"]),
    ("Rabobank", "nl,us,au", [], ["rabobank"]),
    ("ABN AMRO", "nl,uk", [], ["abnamro"]),
    ("Nomura", "jp,uk,us,in,sg,hk", ["workday:nomura"], ["nomura"]),
    ("Mizuho", "jp,us,uk,sg,hk", ["workday:mizuho"], ["mizuho"]),
    ("MUFG", "jp,us,uk,sg,hk", ["workday:mufg"], ["mufg", "mufgbank"]),
    ("SMBC Nikko", "jp,uk,us,hk", [], ["smbcnikko", "smbc"]),
    ("Daiwa Securities", "jp,uk,us,hk", [], ["daiwa", "daiwasecurities"]),
    ("RBC Capital Markets", "ca,us,uk,au", ["workday:rbc"], ["rbc", "royalbank"]),
    ("BMO Capital Markets", "ca,us,uk", ["workday:bmo"], ["bmo", "bankofmontreal"]),
    ("TD Securities", "ca,us,uk,sg", ["workday:td"], ["tdsecurities", "td"]),
    ("Scotiabank", "ca,us,uk", ["workday:scotiabank"], ["scotiabank"]),
    ("CIBC", "ca,us,uk", ["workday:cibc"], ["cibc"]),
    ("Macquarie Group", "au,uk,us,sg,hk,in", ["workday:macquarie"], ["macquarie"]),
    ("Standard Chartered", "uk,sg,hk,in,ae", ["workday:standardchartered"], ["standardchartered", "scb"]),
    ("Jefferies", "us,uk,hk,sg,in", ["workday:jefferies"], ["jefferies"]),
    ("Lazard", "us,uk,fr", [], ["lazard"]),
    ("Wells Fargo", "us,uk,in", ["workday:wellsfargo"], ["wellsfargo"]),
    ("BNY", "us,uk,in,pl,ie", ["workday:bny"], ["bny", "bnymellon"]),
    ("Northern Trust", "us,uk,ie,in", ["workday:northerntrust"], ["northerntrust"]),
    ("Nordea", "fi,se,dk,no,pl", [], ["nordea"]),
    ("SEB", "se,uk,lt", [], ["seb", "sebgroup"]),
    ("Danske Bank", "dk,uk,lt,in", [], ["danskebank"]),
    ("DNB", "no,uk", [], ["dnb"]),
    ("Commerzbank", "de,uk,pl", [], ["commerzbank"]),
    ("UniCredit", "it,de,at", [], ["unicredit"]),
    ("Intesa Sanpaolo", "it,uk", [], ["intesasanpaolo", "intesa"]),
    ("Mediobanca", "it,uk", [], ["mediobanca"]),
    ("Julius Baer", "ch,sg,hk", [], ["juliusbaer"]),
    ("Pictet", "ch,uk,sg,hk", [], ["pictet"]),
    ("Lombard Odier", "ch,uk,sg,hk", [], ["lombardodier"]),
    ("Vontobel", "ch,uk,us", [], ["vontobel"]),
    ("Zurcher Kantonalbank", "ch", [], ["zkb"]),
    ("Erste Group", "at,cz,ro", [], ["erstegroup", "erste"]),
    ("KBC", "be,cz,hu", [], ["kbc", "kbcgroup"]),
    ("Belfius", "be", [], ["belfius"]),
    ("DBS Bank", "sg,hk,in,cn", ["workday:dbs"], ["dbs", "dbsbank"]),
    ("OCBC", "sg,hk,cn", [], ["ocbc"]),
    ("UOB", "sg,my,th", [], ["uob", "uobgroup"]),
    ("Maybank", "my,sg", [], ["maybank"]),
    ("CIMB", "my,sg", [], ["cimb"]),
    ("CICC", "cn,hk,uk,us", [], ["cicc"]),
    ("CITIC Securities", "cn,hk", [], ["citicsecurities"]),
    ("Huatai Securities", "cn,hk,us", [], ["huatai"]),
    ("Guotai Junan", "cn,hk", [], ["guotaijunan"]),
    ("Itau BBA", "br,us,uk", [], ["itau", "itaubba"]),
    ("BTG Pactual", "br,us,uk", [], ["btgpactual", "btg"]),
    ("XP Inc.", "br,us", [], ["xpinc", "xp"]),
]

# --------------------------------------------------------------------------
# EXCHANGES / MARKET INFRASTRUCTURE
# --------------------------------------------------------------------------
EXCHANGE = [
    ("CME Group", "us,uk,sg,in", ["workday:cmegroup"], ["cmegroup", "cme"]),
    ("Intercontinental Exchange", "us,uk,sg,in,il", ["workday:ice"], ["ice", "theice", "intercontinentalexchange"]),
    ("Nasdaq", "us,se,uk,in,lt", ["workday:nasdaq"], ["nasdaq"]),
    ("NYSE", "us", [], ["nyse"]),
    ("Cboe Global Markets", "us,uk,nl,jp,au,ph", ["workday:cboe"], ["cboe"]),
    ("London Stock Exchange Group", "uk,us,in,sg,ro", ["workday:lseg"], ["lseg", "londonstockexchange"]),
    ("Deutsche Boerse", "de,lu,cz,in", [], ["deutscheboerse", "eurex"]),
    ("Euronext", "nl,fr,be,pt,no,it", [], ["euronext"]),
    ("SIX Group", "ch,es", [], ["sixgroup", "six"]),
    ("Hong Kong Exchanges and Clearing", "hk,cn,uk", [], ["hkex"]),
    ("Singapore Exchange", "sg", [], ["sgx", "singaporeexchange"]),
    ("Japan Exchange Group", "jp", [], ["jpx"]),
    ("ASX", "au", [], ["asx"]),
    ("TMX Group", "ca,uk", [], ["tmx", "tmxgroup"]),
    ("B3", "br", [], ["b3"]),
    ("MIAX", "us", [], ["miax", "miaxglobal"]),
    ("IEX", "us", ["greenhouse:iex"], ["iex", "iextrading"]),
    ("MEMX", "us", ["greenhouse:memx"], ["memx"]),
    ("Tradeweb", "us,uk,jp,hk", ["greenhouse:tradeweb"], ["tradeweb"]),
    ("MarketAxess", "us,uk,sg,nl", ["greenhouse:marketaxess"], ["marketaxess"]),
    ("Clear Street", "us,uk", ["greenhouse:clearstreet"], ["clearstreet"]),
    ("Hidden Road", "us,uk,sg,hk", ["greenhouse:hiddenroad"], ["hiddenroad"]),
    ("Marex", "uk,us,sg,hk", ["workday:marex"], ["marex"]),
    ("StoneX Group", "us,uk,sg,br", ["workday:stonex"], ["stonex"]),
    ("Interactive Brokers", "us,uk,hk,sg,in,ch", ["workday:interactivebrokers"], ["interactivebrokers", "ibkr"]),
    ("Virtu ITG", "us,uk,hk", [], ["itg", "virtuitg"]),
    ("Quantitative Brokers", "us,uk,in,au", ["greenhouse:quantitativebrokers"], ["quantitativebrokers"]),
    ("Instinet", "us,uk,hk,jp", [], ["instinet"]),
    ("Liquidnet", "us,uk,sg,hk", [], ["liquidnet"]),
    ("Apex Fintech Solutions", "us", ["greenhouse:apexfintechsolutions"], ["apexclearing", "apexfintech"]),
    ("Broadridge", "us,uk,in,ca", ["workday:broadridge"], ["broadridge"]),
    ("SS&C Technologies", "us,uk,in,ca", ["workday:ssctech"], ["ssctech", "ssnc"]),
    ("FIS", "us,uk,in", ["workday:fis"], ["fis", "fisglobal"]),
    ("Fiserv", "us,uk,in", ["workday:fiserv"], ["fiserv"]),
    ("Citco", "lu,ie,ca,in", [], ["citco"]),
    ("Enfusion", "us,uk,sg,in", ["greenhouse:enfusion"], ["enfusion"]),
    ("Murex", "fr,uk,sg,us", [], ["murex"]),
    ("Numerix", "us,uk,jp", [], ["numerix"]),
    ("ION Group", "it,uk,us,in", [], ["iongroup", "iontrading"]),
    ("Bloomberg", "us,uk,sg,hk,in", ["html:https://careers.bloomberg.com/job/search"], ["bloomberg", "bloomberglp"]),
    ("MSCI", "us,uk,hu,in,mx", ["workday:msci"], ["msci"]),
    ("S&P Global", "us,uk,in,pl", ["workday:spglobal"], ["spglobal", "standardandpoors"]),
    ("Moody's", "us,uk,cz,in", ["workday:moodys"], ["moodys"]),
    ("Morningstar", "us,uk,in,cn", ["workday:morningstar"], ["morningstar"]),
    ("FactSet", "us,uk,in,fr", ["workday:factset"], ["factset"]),
    ("Databento", "us", ["ashby:databento"], ["databento"]),
    ("Polygon.io", "us", ["ashby:polygon"], ["polygonio", "polygon"]),
    ("Kaiko", "fr,uk,us,sg", [], ["kaiko"]),
    ("Exabel", "no,uk", [], ["exabel"]),
]

# --------------------------------------------------------------------------
# FINTECH / TECH WITH QUANT-ADJACENT SEATS
# --------------------------------------------------------------------------
FINTECH = [
    ("Robinhood", "us,uk", ["greenhouse:robinhood"], ["robinhood"]),
    ("Charles Schwab", "us,uk", ["workday:schwab"], ["schwab", "charlesschwab"]),
    ("Webull", "us,sg,hk", [], ["webull"]),
    ("eToro", "il,uk,cy", ["greenhouse:etoro"], ["etoro"]),
    ("IG Group", "uk,au,sg,de", ["greenhouse:iggroup"], ["iggroup", "ig"]),
    ("CMC Markets", "uk,au,sg", [], ["cmcmarkets"]),
    ("Plus500", "il,uk,cy,au", [], ["plus500"]),
    ("Saxo Bank", "dk,uk,sg", [], ["saxobank", "saxo"]),
    ("Tastytrade", "us", [], ["tastytrade", "tastyworks"]),
    ("Stripe", "us,ie,sg,in", ["greenhouse:stripe"], ["stripe"]),
    ("Plaid", "us,uk", ["greenhouse:plaid"], ["plaid"]),
    ("Ramp", "us,uk", ["ashby:ramp"], ["ramp"]),
    ("Brex", "us,ca", ["greenhouse:brex"], ["brex"]),
    ("Mercury", "us", ["ashby:mercury"], ["mercury"]),
    ("Modern Treasury", "us", ["greenhouse:moderntreasury"], ["moderntreasury"]),
    ("Affirm", "us,ca,pl,es", ["greenhouse:affirm"], ["affirm"]),
    ("Marqeta", "us,uk", ["greenhouse:marqeta"], ["marqeta"]),
    ("Chime", "us", ["greenhouse:chime"], ["chime"]),
    ("Revolut", "uk,pl,pt,in", ["html:https://www.revolut.com/careers/"], ["revolut"]),
    ("Monzo", "uk,ie,us", ["greenhouse:monzo"], ["monzo"]),
    ("Starling Bank", "uk,ie", [], ["starlingbank", "starling"]),
    ("N26", "de,es", ["greenhouse:n26"], ["n26"]),
    ("Wise", "uk,ee,sg,hu", ["greenhouse:wise"], ["wise", "transferwise"]),
    ("Klarna", "se,de,uk,us", ["greenhouse:klarna"], ["klarna"]),
    ("Adyen", "nl,us,sg,es", ["greenhouse:adyen"], ["adyen"]),
    ("Checkout.com", "uk,ae,us", ["greenhouse:checkoutcom"], ["checkoutcom", "checkout"]),
    ("Airwallex", "au,hk,sg,uk", ["greenhouse:airwallex"], ["airwallex"]),
    ("Nubank", "br,mx,co,us", ["greenhouse:nubank"], ["nubank"]),
    ("SoFi", "us", ["greenhouse:sofi"], ["sofi"]),
    ("Betterment", "us", ["greenhouse:betterment"], ["betterment"]),
    ("Wealthfront", "us", ["greenhouse:wealthfront"], ["wealthfront"]),
    ("Alpaca", "us,jp", ["ashby:alpaca"], ["alpaca", "alpacamarkets"]),
    ("QuantConnect", "us", [], ["quantconnect"]),
    ("Composer", "us", [], ["composer", "composertrade"]),
    ("Titan", "us", [], ["titanvest", "titan"]),
]

# --------------------------------------------------------------------------
# CRYPTO / DIGITAL ASSET TRADING
# --------------------------------------------------------------------------
CRYPTO = [
    ("Jump Crypto", "us,uk,sg", [], ["jumpcrypto"]),
    ("Wintermute", "uk,sg", ["greenhouse:wintermute"], ["wintermute", "wintermutetrading"]),
    ("GSR Markets", "uk,sg,us,ch", ["greenhouse:gsr"], ["gsr", "gsrmarkets"]),
    ("Amber Group", "sg,hk,us", ["lever:ambergroup"], ["ambergroup", "amber"]),
    ("Auros", "sg,uk,au", [], ["auros", "aurosglobal"]),
    ("Keyrock", "be,sg,uk", ["greenhouse:keyrock"], ["keyrock"]),
    ("B2C2", "uk,us,jp,sg", ["greenhouse:b2c2"], ["b2c2"]),
    ("Cumberland", "us,uk,sg", [], ["cumberland", "cumberlandmining"]),
    ("Galaxy Digital", "us,uk,sg,hk", ["greenhouse:galaxydigital"], ["galaxydigital", "galaxy"]),
    ("Selini Capital", "sg,ae", [], ["selinicapital"]),
    ("Coinbase", "us,uk,ie,sg,in", ["greenhouse:coinbase"], ["coinbase"]),
    ("Kraken", "us,uk,ca,jp", ["greenhouse:kraken"], ["kraken", "payward"]),
    ("Gemini", "us,uk,sg,ie", ["greenhouse:gemini"], ["gemini"]),
    ("OKX", "hk,sg,ae,us", ["lever:okx"], ["okx", "okcoin"]),
    ("Bybit", "ae,sg,hk", [], ["bybit"]),
    ("Circle", "us,uk,ie,sg", ["greenhouse:circle"], ["circle", "circleinternet"]),
    ("Ripple", "us,uk,sg,ae", ["greenhouse:ripple"], ["ripple"]),
    ("Anchorage Digital", "us,pt,sg", ["greenhouse:anchoragedigital"], ["anchoragedigital"]),
    ("Fireblocks", "il,us,uk,sg", ["greenhouse:fireblocks"], ["fireblocks"]),
    ("Chainalysis", "us,uk,dk,sg", ["greenhouse:chainalysis"], ["chainalysis"]),
    ("Paxos", "us,sg,il", ["greenhouse:paxos"], ["paxos"]),
    ("BitGo", "us,de,sg", ["greenhouse:bitgo"], ["bitgo"]),
    ("Copper.co", "uk,ch,ae", ["greenhouse:copper"], ["copperco", "copper"]),
    ("FalconX", "us,in,sg,uk", ["greenhouse:falconx"], ["falconx"]),
    ("Talos", "us,uk,sg", ["greenhouse:talos"], ["talos", "talostrading"]),
]

# --------------------------------------------------------------------------
# SECOND WAVE - the smaller shops, regional desks and specialists that the
# first pass skipped. This is where most of the roles nobody else is watching
# actually live.
# --------------------------------------------------------------------------

PROP_2 = [
    # US - Chicago / Midwest
    ("DV Trading", "us,ca,uk", [], ["dvtrading", "dvtrading-llc"]),
    ("Nico Trading", "us", [], ["nicotrading", "nicoholdings"]),
    ("WH Trading", "us", [], ["whtrading"]),
    ("Ketchum Trading", "us", [], ["ketchumtrading"]),
    ("Great Point Capital", "us", [], ["greatpointcapital"]),
    ("3Red Partners", "us", [], ["3redpartners", "threeredpartners"]),
    ("Traditum Group", "us", [], ["traditum"]),
    ("Optiver US", "us", [], ["optiverus"]),
    ("Tradelink Securities", "us", [], ["tradelink", "tradelinksecurities"]),
    ("CMT Group", "us", [], ["cmtgroup", "chicagomercantiletrading"]),
    ("Blue Capital Group", "us", [], ["bluecapitalgroup"]),
    ("Arb Trading Group", "us", [], ["arbtrading", "arbtradinggroup"]),
    ("Endeavour Trading", "us", [], ["endeavourtrading"]),
    ("Rock Trading", "us", [], ["rocktrading"]),
    # US - other
    ("TGS Management", "us", [], ["tgsmanagement", "tgs"]),
    ("Stevens Capital Management", "us", [], ["stevenscapital", "scm-lp"]),
    ("BlackEdge Capital", "us", [], ["blackedgecapital"]),
    ("Cheiron Trading", "us,sg", [], ["cheirontrading"]),
    ("Tyler Capital", "us,uk", [], ["tylercapital"]),
    ("Convexity", "us", [], ["convexity", "convexitycapital"]),
    ("Susquehanna Private Equity", "us", [], ["sigpe"]),
    ("Seven Eight Capital", "us", [], ["seveneightcapital"]),
    ("Tsagas Capital", "us", [], ["tsagascapital"]),
    ("Wintrust? placeholder", "us", [], []),  # pruned below
    ("PDT Capital", "us", [], ["pdtcapital"]),
    ("Beacon Platform", "us,uk", ["greenhouse:beaconplatform"], ["beaconplatform", "beacon"]),
    ("Domeyard", "us", [], ["domeyard"]),
    ("Pico Quantitative Trading", "us", [], ["picotrading"]),
    ("Jane Street Capital Asia", "hk", [], ["janestreetasia"]),
    # Europe
    ("Optiver Europe", "nl", [], ["optivereurope"]),
    ("Mint Tower Capital Management", "nl", [], ["minttower"]),
    ("Scientific Trading", "nl", [], ["scientifictrading"]),
    ("Nyenburgh Holding", "nl", [], ["nyenburgh"]),
    ("360 Trading Networks", "de,in", [], ["360t", "360trading"]),
    ("Tibra Trading Europe", "uk", [], ["tibraeurope"]),
    ("Qube RT Europe", "fr", [], ["quberteurope"]),
    ("ETS Trading", "at,de", [], ["etstrading", "ets"]),
    ("Rentablo? placeholder", "de", [], []),  # pruned below
    ("Quantitative Systematic Strategies", "uk", [], ["qssgroup"]),
    ("Bluecrest Capital Management", "uk,us,ch,sg", [], ["bluecrest", "bluecrestcapital"]),
    ("Millburn Ridgefield", "us", [], ["millburn", "millburnridgefield"]),
    ("Sussex Partners", "uk", [], ["sussexpartners"]),
    ("Marex Solutions", "uk", [], ["marexsolutions"]),
    ("Vivienne Investissement", "fr", [], ["vivienneinvestissement"]),
    ("Sun Trading Europe", "uk", [], ["suntradingeurope"]),
    ("Tradition", "ch,uk,us,sg", [], ["tradition", "tradition-group"]),
    ("Ardea Partners", "us,uk", [], ["ardeapartners"]),
    # APAC
    ("Optiver Asia Pacific", "au,hk,sg,tw", [], ["optiverapac"]),
    ("Vivcourt Trading", "au", [], ["vivcourt"]),
    ("Akuna Capital Sydney", "au", [], ["akunasydney"]),
    ("Zeta Trading", "au", [], ["zetatrading"]),
    ("Propex Derivatives", "au", [], ["propex", "propexderivatives"]),
    ("Blackcore Trading", "au", [], ["blackcoretrading"]),
    ("IMC Asia Pacific", "sg,hk", [], ["imcapac"]),
    ("Grasshopper Trading", "sg", [], ["grasshoppertrading"]),
    ("Sentosa Capital", "sg", [], ["sentosacapital"]),
    ("Taurus Trading", "sg", [], ["taurustrading"]),
    ("Kronos Research", "tw,sg", [], ["kronosresearch", "kronos"]),
    ("Presto Labs", "kr,sg", [], ["prestolabs", "presto"]),
    ("Nine Mile Trading", "au", [], ["ninemiletrading"]),
    # India
    ("Tower Research Capital India", "in", [], ["towerresearchindia"]),
    ("Squarepoint India", "in", [], ["squarepointindia"]),
    ("Mansa Capital", "in", [], ["mansacapital"]),
    ("Quant Capital", "in", [], ["quantcapital"]),
    ("Hillroute Capital", "in,ae", [], ["hillroute"]),
    ("Sacred Capital", "in", [], ["sacredcapital"]),
    ("Tradesocio? placeholder", "in", [], []),  # pruned below
]

FUND_2 = [
    # Systematic / CTA
    ("Crabel Capital Management", "us,uk,jp", [], ["crabel", "crabelcapital"]),
    ("Graham Capital Management", "us", [], ["grahamcapital", "grahamcm"]),
    ("Campbell & Company", "us", [], ["campbellandcompany", "campbellco"]),
    ("Quantitative Investment Management", "us", [], ["qiminvest", "qim"]),
    ("ISAM", "uk,us", [], ["isam", "isamfunds"]),
    ("Transtrend", "nl", [], ["transtrend"]),
    ("Lynx Asset Management", "se,uk", [], ["lynxassetmanagement", "lynxhedge"]),
    ("Brummer & Partners", "se,uk,sg", [], ["brummer", "brummerandpartners"]),
    ("RPM Risk & Portfolio Management", "se", [], ["rpm", "rpmrisk"]),
    ("Informed Portfolio Management", "se", [], ["ipmswe", "informedportfolio"]),
    ("Nordkinn Asset Management", "no,se", [], ["nordkinn"]),
    ("Quantica Capital", "ch", [], ["quanticacapital"]),
    ("Welton Investment Partners", "us", [], ["welton", "weltoninvestment"]),
    ("Dunn Capital Management", "us", [], ["dunncapital"]),
    ("Chesapeake Capital", "us", [], ["chesapeakecapital"]),
    ("Mulvaney Capital Management", "uk", [], ["mulvaneycapital"]),
    ("Abraham Trading Company", "us", [], ["abrahamtrading"]),
    ("Sandbar Asset Management", "uk", [], ["sandbarasset"]),
    ("Fort LP", "us", [], ["fortlp", "fortinvestment"]),
    ("GAM Systematic", "uk,ch", [], ["gamsystematic", "gam"]),
    ("Aspect Diversified", "uk", [], ["aspectdiversified"]),
    ("Eclipse Capital Management", "us", [], ["eclipsecapital"]),
    ("Polar Asset Management", "ca", [], ["polarasset", "polarassetmanagement"]),
    ("Ramius? placeholder", "us", [], []),  # pruned below
    # Multi-strat / pod shops and event driven
    ("Weiss Multi-Strategy Advisers", "us", [], ["weissmulti", "gweiss"]),
    ("Ellington Management Group", "us", [], ["ellingtonmgmt", "ellington"]),
    ("Pine River Capital Management", "us,uk,hk", [], ["pineriver", "prcm"]),
    ("Saba Capital Management", "us,uk", [], ["sabacapital"]),
    ("Whitebox Advisors", "us", [], ["whiteboxadvisors"]),
    ("Napier Park Global Capital", "us,uk", [], ["napierpark"]),
    ("Palmer Square Capital Management", "us", [], ["palmersquare"]),
    ("Beach Point Capital", "us,uk", [], ["beachpointcapital"]),
    ("Canyon Partners", "us,uk", [], ["canyonpartners"]),
    ("Redwood Capital Management", "us", [], ["redwoodcapital"]),
    ("Knighthead Capital", "us,uk", [], ["knightheadcapital"]),
    ("Monarch Alternative Capital", "us,uk", [], ["monarchalternative"]),
    ("Avenue Capital Group", "us,uk,sg", [], ["avenuecapital"]),
    ("Centerbridge Partners", "us,uk", [], ["centerbridge"]),
    ("GoldenTree Asset Management", "us,uk,sg", [], ["goldentree"]),
    ("Fir Tree Partners", "us", [], ["firtreepartners"]),
    ("Arena Investors", "us,uk", [], ["arenainvestors"]),
    ("Mariner Investment Group", "us", [], ["marinerinvestment"]),
    ("Axonic Capital", "us", [], ["axoniccapital"]),
    ("Hein Park Capital", "us", [], ["heinpark"]),
    ("Lighthouse Investment Partners", "us,uk", [], ["lighthousepartners"]),
    ("Sona Asset Management", "uk", [], ["sonaasset"]),
    ("Kite Lake Capital", "uk", [], ["kitelake"]),
    ("Melqart Asset Management", "uk", [], ["melqart"]),
    ("Syquant Capital", "fr", [], ["syquant"]),
    ("Boussard & Gavaudan", "uk,fr", [], ["bgam", "boussardgavaudan"]),
    ("Tyrus Capital", "mc,uk", [], ["tyruscapital"]),
    ("Naya Capital Management", "uk", [], ["nayacapital"]),
    ("Marble Bar Asset Management", "uk", [], ["marblebar", "mbam"]),
    ("Pertento Partners", "uk", [], ["pertento"]),
    ("Glen Point Capital", "uk", [], ["glenpoint"]),
    ("Astaris Capital", "uk", [], ["astariscapital"]),
    ("Trium Alternatives", "uk", [], ["triumalternatives"]),
    ("CastleKnight Management", "us", [], ["castleknight"]),
    ("Balyasny Europe", "uk", [], ["balyasnyeurope"]),
    # Long/short and activist
    ("Pershing Square Capital", "us", [], ["pershingsquare"]),
    ("Greenlight Capital", "us", [], ["greenlightcapital"]),
    ("Glenview Capital Management", "us", [], ["glenviewcapital"]),
    ("Starboard Value", "us", [], ["starboardvalue"]),
    ("Trian Partners", "us", [], ["trianpartners"]),
    ("ValueAct Capital", "us,uk", [], ["valueactcapital"]),
    ("Corvex Management", "us", [], ["corvexmanagement"]),
    ("Sachem Head Capital", "us", [], ["sachemhead"]),
    ("Senator Investment Group", "us", [], ["senatorinvestment"]),
    ("Select Equity Group", "us", [], ["selectequity"]),
    ("Egerton Capital", "uk", [], ["egertoncapital"]),
    ("TCI Fund Management", "uk", [], ["tcifund"]),
    ("Marathon Trading", "us", [], ["marathontrading"]),
    # Asia
    ("Anatole Investment Management", "hk", [], ["anatoleinvestment"]),
    ("Golden Pine Capital", "hk", [], ["goldenpinecapital"]),
    ("Keywise Capital", "hk", [], ["keywisecapital"]),
    ("Greenwoods Asset Management", "cn,hk,sg", [], ["greenwoodsasset"]),
    ("Panview Capital", "hk", [], ["panviewcapital"]),
    ("Zeal Asset Management", "hk", [], ["zealasset"]),
    ("Trivest Advisors", "hk", [], ["trivestadvisors"]),
    ("Athos Capital", "hk", [], ["athoscapital"]),
    ("Blue Pool Capital", "hk", [], ["bluepoolcapital"]),
    ("Janchor Partners", "hk", [], ["janchorpartners"]),
    ("Ward Ferry Management", "hk", [], ["wardferry"]),
    ("Karst Peak Capital", "hk", [], ["karstpeak"]),
    ("Torq Capital Management", "hk", [], ["torqcapital"]),
    ("Nine Masts Capital", "hk", [], ["ninemasts"]),
    ("Double Haven Capital", "hk", [], ["doublehaven"]),
    ("LIM Advisors", "hk", [], ["limadvisors"]),
    ("Value Partners Group", "hk,sg,cn", [], ["valuepartners"]),
    ("CloudAlpha Capital", "hk", [], ["cloudalpha"]),
    ("Tairen Capital", "cn,hk", [], ["tairencapital"]),
    ("Springs Capital", "cn,hk", [], ["springscapital"]),
    ("Vantage Point Asset Management", "sg", [], ["vantagepointasset"]),
    ("Asia Research & Capital Management", "hk", [], ["arcm", "asiaresearchcapital"]),
    # China quant
    ("High-Flyer Quant", "cn", [], ["highflyer", "highflyerquant"]),
    ("Ubiquant Investment", "cn", [], ["ubiquant"]),
    ("Minghong Investment", "cn", [], ["minghong"]),
    ("Lingjun Investment", "cn", [], ["lingjun"]),
    ("Yanfu Investments", "cn", [], ["yanfu"]),
    ("Mingshi Investment Management", "cn,hk,uk", [], ["mingshi"]),
    ("Baiont Quant", "cn", [], ["baiont", "baiontquant"]),
    ("Panyao Capital", "cn", [], ["panyaocapital"]),
    # Traditional AM
    ("Franklin Templeton", "us,uk,in,sg", ["workday:franklintempleton"], ["franklintempleton"]),
    ("PGIM", "us,uk,jp,sg", ["workday:prudential"], ["pgim"]),
    ("AllianceBernstein", "us,uk,in,sg", ["workday:alliancebernstein"], ["alliancebernstein", "ab"]),
    ("DWS Group", "de,uk,us", [], ["dws", "dwsgroup"]),
    ("Allianz Global Investors", "de,uk,us,hk", [], ["allianzgi", "allianzglobalinvestors"]),
    ("Columbia Threadneedle", "us,uk,lu", [], ["columbiathreadneedle"]),
    ("Federated Hermes", "us,uk", [], ["federatedhermes"]),
    ("Artisan Partners", "us,uk", [], ["artisanpartners"]),
    ("Dodge & Cox", "us,uk", [], ["dodgeandcox", "dodgecox"]),
    ("American Century Investments", "us,uk,hk", [], ["americancentury"]),
    ("Loomis Sayles", "us,uk,sg", [], ["loomissayles"]),
    ("Principal Financial Group", "us,uk,in,hk", ["workday:principal"], ["principal"]),
    ("Voya Investment Management", "us", [], ["voya"]),
    ("Fisher Investments", "us,uk,de", ["workday:fisherinvestments"], ["fisherinvestments"]),
    ("Russell Investments", "us,uk,au,cn", [], ["russellinvestments"]),
    ("Fiera Capital", "ca,uk,us", [], ["fieracapital"]),
    ("CI Financial", "ca,us", [], ["cifinancial"]),
    ("Mackenzie Investments", "ca", [], ["mackenzieinvestments"]),
    ("Nikko Asset Management", "jp,sg,uk", [], ["nikkoam"]),
    ("Nomura Asset Management", "jp,uk,sg", [], ["nomuraam"]),
    ("Eastspring Investments", "sg,hk,jp,in", [], ["eastspring"]),
    ("Fullerton Fund Management", "sg", [], ["fullertonfund"]),
    ("Lion Global Investors", "sg", [], ["lionglobalinvestors"]),
    ("China Asset Management", "cn,hk", [], ["chinaamc"]),
    ("E Fund Management", "cn,hk", [], ["efundmanagement"]),
    ("Harvest Fund Management", "cn,hk", [], ["harvestfund"]),
    ("Bosera Asset Management", "cn,hk", [], ["boseraasset"]),
    ("Mirae Asset Global Investments", "kr,us,uk,in", [], ["miraeasset"]),
    ("Samsung Asset Management", "kr", [], ["samsungasset"]),
]

BANK_2 = [
    ("NatWest Group", "uk,pl,in", ["workday:natwest"], ["natwest", "natwestgroup", "rbs"]),
    ("Lloyds Banking Group", "uk", ["workday:lloydsbanking"], ["lloydsbank", "lloyds"]),
    ("Cantor Fitzgerald", "us,uk,hk", [], ["cantorfitzgerald", "cantor"]),
    ("BGC Group", "us,uk,sg", [], ["bgcpartners", "bgcgroup"]),
    ("TP ICAP", "uk,us,sg", [], ["tpicap"]),
    ("Oppenheimer & Co.", "us,uk", [], ["oppenheimer"]),
    ("Piper Sandler", "us,uk", [], ["pipersandler"]),
    ("Raymond James", "us,uk,ca", [], ["raymondjames"]),
    ("Stifel Financial", "us,uk,de", [], ["stifel"]),
    ("Guggenheim Partners", "us,uk", [], ["guggenheimpartners"]),
    ("William Blair", "us,uk", [], ["williamblair"]),
    ("Robert W. Baird", "us,uk", [], ["rwbaird", "baird"]),
    ("Houlihan Lokey", "us,uk,hk", [], ["houlihanlokey"]),
    ("Moelis & Company", "us,uk,hk", [], ["moelis"]),
    ("PJT Partners", "us,uk,hk", [], ["pjtpartners"]),
    ("Perella Weinberg Partners", "us,uk", [], ["pwpartners", "perellaweinberg"]),
    ("Rothschild & Co", "uk,fr,us", [], ["rothschildandco", "rothschild"]),
    ("Evercore", "us,uk,hk", [], ["evercore"]),
    ("Truist Securities", "us", ["workday:truist"], ["truist"]),
    ("PNC Financial Services", "us", ["workday:pnc"], ["pnc"]),
    ("U.S. Bancorp", "us", ["workday:usbank"], ["usbank", "usbancorp"]),
    ("Citizens Financial Group", "us", ["workday:citizensbank"], ["citizensbank"]),
    ("Fifth Third Bank", "us", [], ["fifththird", "53"]),
    ("KeyBank", "us", [], ["keybank", "key"]),
    ("M&T Bank", "us", [], ["mtb", "mandtbank"]),
    ("Regions Financial", "us", [], ["regions", "regionsbank"]),
    ("Handelsbanken", "se,uk", [], ["handelsbanken"]),
    ("Swedbank", "se,lt,ee", [], ["swedbank"]),
    ("CaixaBank", "es", [], ["caixabank"]),
    ("Banco Sabadell", "es,uk", [], ["bancosabadell", "sabadell"]),
    ("Bankinter", "es", [], ["bankinter"]),
    ("Raiffeisen Bank International", "at,ro,cz", [], ["rbinternational", "raiffeisen"]),
    ("AIB", "ie,uk", [], ["aib", "aibgroup"]),
    ("Bank of Ireland", "ie,uk", [], ["bankofireland"]),
    ("Commonwealth Bank of Australia", "au", [], ["commbank", "cba"]),
    ("Westpac", "au,nz", [], ["westpac"]),
    ("ANZ", "au,nz,in", [], ["anz"]),
    ("National Australia Bank", "au", [], ["nab", "nationalaustraliabank"]),
    ("National Bank of Canada", "ca", [], ["nbc", "nationalbankofcanada"]),
    ("Bank of China", "cn,hk,uk", [], ["bankofchina"]),
    ("ICBC", "cn,hk,uk", [], ["icbc"]),
    ("China Construction Bank", "cn,hk", [], ["ccb", "chinaconstructionbank"]),
    ("Shinhan Investment", "kr", [], ["shinhaninvest", "shinhan"]),
    ("Samsung Securities", "kr", [], ["samsungsecurities"]),
    ("Mirae Asset Securities", "kr,hk,us", [], ["miraeassetsecurities"]),
    ("NH Investment & Securities", "kr", [], ["nhis", "nhqv"]),
    ("SBI Securities", "jp", [], ["sbisec", "sbisecurities"]),
    ("Monex Group", "jp,us", [], ["monexgroup", "monex"]),
    ("Rakuten Securities", "jp", [], ["rakutensec"]),
    ("Okasan Securities", "jp", [], ["okasan"]),
    ("Emirates NBD", "ae,in,uk", [], ["emiratesnbd"]),
    ("First Abu Dhabi Bank", "ae,uk,sg", [], ["bankfab", "fab"]),
    ("Qatar National Bank", "qa,uk", [], ["qnb"]),
    ("Bradesco BBI", "br", [], ["bradesco", "bradescobbi"]),
    ("Banco Safra", "br", [], ["bancosafra", "safra"]),
    ("Nuvama Wealth", "in", [], ["nuvama"]),
    ("Edelweiss Financial Services", "in", [], ["edelweiss", "edelweissfin"]),
    ("Kotak Securities", "in", [], ["kotaksecurities", "kotak"]),
    ("ICICI Securities", "in", [], ["icicisecurities", "icicibank"]),
    ("Axis Capital", "in", [], ["axiscapital", "axisbank"]),
    ("Motilal Oswal", "in", [], ["motilaloswal"]),
    ("Zerodha", "in", [], ["zerodha"]),
    ("Groww", "in", [], ["groww"]),
    ("Angel One", "in", [], ["angelone", "angelbroking"]),
]

EXCHANGE_2 = [
    ("DTCC", "us,uk,in,ie", ["workday:dtcc"], ["dtcc"]),
    ("Euroclear", "be,uk,fr,pl", [], ["euroclear"]),
    ("Clearstream", "lu,de", [], ["clearstream"]),
    ("Options Clearing Corporation", "us", [], ["theocc", "occ"]),
    ("LCH", "uk,fr,us", [], ["lch", "lchclearnet"]),
    ("Eurex", "de,ch,uk", [], ["eurex"]),
    ("BOX Exchange", "us", [], ["boxexchange", "boxoptions"]),
    ("Long-Term Stock Exchange", "us", [], ["ltse"]),
    ("OneChronos", "us", ["greenhouse:onechronos"], ["onechronos"]),
    ("PrimaryBid", "uk", [], ["primarybid"]),
    ("Aquis Exchange", "uk,fr", [], ["aquisexchange", "aquis"]),
    ("Turquoise", "uk", [], ["turquoise"]),
    ("Bursa Malaysia", "my", [], ["bursamalaysia"]),
    ("Philippine Stock Exchange", "ph", [], ["pse"]),
    ("Indonesia Stock Exchange", "id", [], ["idx"]),
    ("National Stock Exchange of India", "in", [], ["nseindia", "nse"]),
    ("BSE Limited", "in", [], ["bseindia", "bse"]),
    ("Korea Exchange", "kr", [], ["krx", "koreaexchange"]),
    ("Taiwan Stock Exchange", "tw", [], ["twse"]),
    ("Tel Aviv Stock Exchange", "il", [], ["tase"]),
    ("Johannesburg Stock Exchange", "za", [], ["jse"]),
    ("Borsa Istanbul", "tr", [], ["borsaistanbul"]),
    ("Moscow Exchange", "ru", [], ["moex"]),
    # Infrastructure & data vendors
    ("KX", "uk,ie,us,sg", ["greenhouse:kx"], ["kx", "kxsystems", "firstderivatives"]),
    ("Arcesium", "us,in,uk", ["greenhouse:arcesium"], ["arcesium"]),
    ("Clearwater Analytics", "us,uk,in", ["greenhouse:clearwateranalytics"], ["clearwateranalytics"]),
    ("SimCorp", "dk,uk,us,sg", [], ["simcorp"]),
    ("TS Imagine", "us,uk,sg,hk", ["greenhouse:tsimagine"], ["tsimagine", "tradingscreen"]),
    ("Trading Technologies", "us,uk,sg,in", ["greenhouse:tradingtechnologies"], ["tradingtechnologies", "tt"]),
    ("CQG", "us,uk", [], ["cqg"]),
    ("Exegy", "us,uk", [], ["exegy"]),
    ("Pico", "us,uk,sg", ["greenhouse:pico"], ["pico", "picoquantitative"]),
    ("Beeks Group", "uk,us", [], ["beeksgroup", "beeks"]),
    ("Options Technology", "uk,us,hk", [], ["optionstechnology", "options-it"]),
    ("OneTick", "us,uk", [], ["onetick", "onemarketdata"]),
    ("dxFeed", "us,de,ua", [], ["dxfeed"]),
    ("Adaptive Financial Consulting", "uk,us", ["greenhouse:adaptive"], ["weareadaptive", "adaptive"]),
    ("Finastra", "uk,us,in,sg", [], ["finastra"]),
    ("Temenos", "ch,uk,in", [], ["temenos"]),
    ("Avaloq", "ch,sg,de", [], ["avaloq"]),
    ("Addepar", "us,uk,in", ["greenhouse:addepar"], ["addepar"]),
    ("Enfusion Europe", "uk", [], ["enfusioneurope"]),
    ("Bloomberg Industry Group", "us,uk", [], ["bloombergindustry"]),
    ("AlphaSense", "us,uk,in,fi", ["greenhouse:alphasense"], ["alphasense"]),
    ("YipitData", "us,uk,in", ["greenhouse:yipitdata"], ["yipitdata"]),
    ("M Science", "us,uk", [], ["mscience"]),
    ("Similarweb", "il,us,uk", ["greenhouse:similarweb"], ["similarweb"]),
    ("Neudata", "uk,us", [], ["neudata"]),
    ("Eagle Alpha", "ie,us", [], ["eaglealpha"]),
    ("Quandl", "ca,us", [], ["quandl"]),
    ("Coin Metrics", "us,uk", ["greenhouse:coinmetrics"], ["coinmetrics"]),
    ("Amberdata", "us,uk", ["greenhouse:amberdata"], ["amberdata"]),
    ("Sigma Broking", "uk", [], ["sigmabroking"]),
    ("ED&F Man Capital", "uk,us", [], ["edfmancapital"]),
    ("R.J. O'Brien", "us,uk", [], ["rjobrien", "rjo"]),
    ("ADM Investor Services", "us,uk", [], ["admis"]),
]

FINTECH_2 = [
    ("Block", "us,au,ca,ie", ["greenhouse:block"], ["block", "squareinc", "square"]),
    ("PayPal", "us,uk,in,sg,ie", ["workday:paypal"], ["paypal"]),
    ("Intuit", "us,in,ca,uk", ["workday:intuit"], ["intuit"]),
    ("Toast", "us,ie,in", ["greenhouse:toast"], ["toast", "toasttab"]),
    ("Shift4", "us,uk", [], ["shift4"]),
    ("Nuvei", "ca,uk,il", [], ["nuvei"]),
    ("Payoneer", "us,il,in,hk", ["greenhouse:payoneer"], ["payoneer"]),
    ("Remitly", "us,ph,in,uk", ["greenhouse:remitly"], ["remitly"]),
    ("dLocal", "uy,br,us,uk", ["greenhouse:dlocal"], ["dlocal"]),
    ("Flutterwave", "ng,us,uk", ["greenhouse:flutterwave"], ["flutterwave"]),
    ("Rapyd", "il,uk,sg", ["greenhouse:rapyd"], ["rapyd"]),
    ("Thunes", "sg,uk,us", [], ["thunes"]),
    ("Ebury", "uk,es,nl", ["greenhouse:ebury"], ["ebury"]),
    ("Corpay", "us,uk", [], ["corpay", "fleetcor"]),
    ("StoneCo", "br", [], ["stoneco", "stone"]),
    ("PagBank PagSeguro", "br", [], ["pagseguro", "pagbank"]),
    ("Mollie", "nl,de,uk", ["greenhouse:mollie"], ["mollie"]),
    ("SumUp", "uk,de,br", ["greenhouse:sumup"], ["sumup"]),
    ("Zopa", "uk", ["greenhouse:zopa"], ["zopa"]),
    ("OakNorth", "uk,in,us", ["greenhouse:oaknorth"], ["oaknorth"]),
    ("Tide", "uk,in,bg", ["greenhouse:tide"], ["tide", "tidebanking"]),
    ("Atom Bank", "uk", [], ["atombank"]),
    ("Trade Republic", "de,uk", ["greenhouse:traderepublic"], ["traderepublic"]),
    ("Scalable Capital", "de,uk,at", ["greenhouse:scalablecapital"], ["scalablecapital"]),
    ("Bitpanda", "at,de,uk", ["greenhouse:bitpanda"], ["bitpanda"]),
    ("Lightyear", "ee,uk", [], ["lightyear"]),
    ("Freetrade", "uk", ["greenhouse:freetrade"], ["freetrade"]),
    ("Trading 212", "uk,bg", [], ["trading212"]),
    ("Hargreaves Lansdown", "uk", [], ["hargreaveslansdown"]),
    ("AJ Bell", "uk", [], ["ajbell"]),
    ("interactive investor", "uk", [], ["interactiveinvestor", "ii"]),
    ("Moneyfarm", "uk,it", [], ["moneyfarm"]),
    ("Raisin", "de,uk,us", ["greenhouse:raisin"], ["raisin"]),
    ("Public.com", "us", ["greenhouse:public"], ["public", "publicholdings"]),
    ("M1 Finance", "us", ["greenhouse:m1finance"], ["m1finance", "m1"]),
    ("Stash", "us", ["greenhouse:stash"], ["stash", "stashinvest"]),
    ("Acorns", "us", ["greenhouse:acorns"], ["acorns"]),
    ("Kalshi", "us", ["ashby:kalshi"], ["kalshi"]),
    ("Polymarket", "us", ["ashby:polymarket"], ["polymarket"]),
    ("Sardine", "us,in", ["ashby:sardine"], ["sardine", "sardineai"]),
    ("Nium", "sg,in,uk,us", ["greenhouse:nium"], ["nium"]),
    ("Grab Financial", "sg,my,id", [], ["grab", "grabfinancial"]),
    ("Sea Group", "sg,id,tw", [], ["seagroup", "sea"]),
    ("Paytm", "in", [], ["paytm"]),
    ("PhonePe", "in", [], ["phonepe"]),
    ("Razorpay", "in,my", ["greenhouse:razorpay"], ["razorpay"]),
    ("CRED", "in", [], ["cred"]),
]

CRYPTO_2 = [
    ("Binance", "ae,sg,fr", [], ["binance"]),
    ("Crypto.com", "sg,uk,us", ["greenhouse:cryptocom"], ["cryptocom", "crypto"]),
    ("KuCoin", "sg,hk", [], ["kucoin"]),
    ("Gate.io", "hk,ae", [], ["gateio", "gate"]),
    ("Bitget", "sg,ae", [], ["bitget"]),
    ("MEXC", "sg,ae", [], ["mexc"]),
    ("Deribit", "nl,ae,pa", [], ["deribit"]),
    ("Bitfinex", "vg,uk,ch", [], ["bitfinex"]),
    ("Bitstamp", "lu,uk,sg", [], ["bitstamp"]),
    ("Flowdesk", "fr,sg,us", ["greenhouse:flowdesk"], ["flowdesk"]),
    ("DWF Labs", "sg,ae,hk", [], ["dwflabs"]),
    ("Portofino Technologies", "ch,uk,sg", ["greenhouse:portofino"], ["portofinotech", "portofino"]),
    ("QCP Capital", "sg,ae", [], ["qcpcapital", "qcp"]),
    ("Arbelos Markets", "us", [], ["arbelosmarkets"]),
    ("Efficient Frontier", "il,sg", [], ["efficientfrontier"]),
    ("Altonomy", "sg,us", [], ["altonomy"]),
    ("Nonco", "us,ar", [], ["nonco"]),
    ("Hex Trust", "hk,sg,ae", [], ["hextrust"]),
    ("Matrixport", "sg,hk", [], ["matrixport"]),
    ("Blockchain.com", "uk,us,sg", ["greenhouse:blockchain"], ["blockchain", "blockchaincom"]),
    ("Zodia Markets", "uk,ie,ae", [], ["zodiamarkets"]),
    ("Bitwise Asset Management", "us", ["greenhouse:bitwise"], ["bitwiseinvestments", "bitwise"]),
    ("Grayscale Investments", "us", ["greenhouse:grayscale"], ["grayscale"]),
    ("Pantera Capital", "us", ["greenhouse:pantera"], ["panteracapital"]),
    ("Polychain Capital", "us", [], ["polychain", "polychaincapital"]),
    ("Multicoin Capital", "us", [], ["multicoincapital"]),
    ("Dragonfly", "us", [], ["dragonflycapital", "dragonfly"]),
    ("Hashed", "kr,sg,us", [], ["hashed"]),
    ("Amber Premium", "sg,hk", [], ["amberpremium"]),
    ("Uniswap Labs", "us", ["greenhouse:uniswaplabs"], ["uniswaplabs", "uniswap"]),
    ("Chainlink Labs", "us,uk,sg", ["greenhouse:chainlinklabs"], ["chainlinklabs", "chainlink"]),
    ("Consensys", "us,uk,ch,sg", ["greenhouse:consensys"], ["consensys"]),
]

CATEGORIES = [
    ("prop", PROP + PROP_2),
    ("fund", FUND + FUND_2),
    ("bank", BANK + BANK_2),
    ("exchange", EXCHANGE + EXCHANGE_2),
    ("fintech", FINTECH + FINTECH_2),
    ("crypto", CRYPTO + CRYPTO_2),
]

# Entries I wasn't confident enough about to ship. A firm that doesn't exist
# costs a wasted probe cycle and then sits in the manual-check panel as noise,
# which is worse than leaving it out.
PRUNE = {"wintrust? placeholder", "rentablo? placeholder", "tradesocio? placeholder",
         "ramius? placeholder"}

STOPWORDS = {
    "the", "group", "inc", "llc", "ltd", "plc", "co", "company", "and",
    "capital", "partners", "management", "asset", "investment", "investments",
    "securities", "advisors", "technologies", "fund", "global", "markets",
}


def slugify(name: str, drop_stopwords: bool = False) -> str:
    s = name.lower()
    s = s.replace("&", "and").replace(".", "").replace("'", "")
    words = re.split(r"[^a-z0-9]+", s)
    words = [w for w in words if w]
    if drop_stopwords:
        kept = [w for w in words if w not in STOPWORDS]
        if kept:
            words = kept
    return "".join(words)


def slug_candidates(name: str, extra: list) -> list:
    cands = []
    for c in extra:
        if c not in cands:
            cands.append(c)
    for c in (slugify(name), slugify(name, drop_stopwords=True),
              slugify(name).replace("", "")):
        if c and c not in cands:
            cands.append(c)
    hyph = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    if hyph not in cands:
        cands.append(hyph)
    return [c for c in cands if len(c) >= 2][:6]


# Where deriving "<first slug>.com" gets the domain wrong. The resolver reads
# these pages to find each firm's real ATS, so a wrong domain costs coverage.
DOMAIN_OVERRIDES = {
    "Susquehanna International Group": "sig.com",
    "D. E. Shaw & Co.": "deshaw.com",
    "Hudson River Trading": "hudsonrivertrading.com",
    "Citadel Securities": "citadelsecurities.com",
    "Citadel": "citadel.com",
    "Jane Street": "janestreet.com",
    "Chicago Trading Company": "chicagotrading.com",
    "PEAK6": "peak6.com",
    "Susquehanna Pacific": "sig.com",
    "Susquehanna Private Equity": "sig.com",
    "Group One Trading": "group1.com",
    "Five Rings": "fiveringsllc.com",
    "Headlands Technologies": "headlandstech.com",
    "Old Mission Capital": "oldmissioncapital.com",
    "Quantlab Financial": "quantlab.com",
    "TransMarket Group": "transmarketgroup.com",
    "Maven Securities": "mavensecurities.com",
    "Da Vinci Trading": "davinciderivatives.com",
    "All Options": "alloptions.nl",
    "Amsterdam Trading Group": "atg.nl",
    "Mako Trading": "mako.com",
    "Liquid Capital": "liquidcapitalgroup.com",
    "OSTC": "ostc.com",
    "Kershner Trading Group": "kershnertrading.com",
    "GTS": "gtsx.com",
    "Tibra Capital": "tibra.com",
    "Vivienne Court Trading": "viviennecourt.com",
    "Graviton Research Capital": "gravitontrading.com",
    "AlphaGrep Securities": "alphagrep.com",
    "NK Securities Research": "nksecurities.com",
    "Estee Advisors": "esteeadvisors.com",
    "Aquatic Capital Management": "aquatic.com",
    "Man Group": "man.com",
    "Two Sigma": "twosigma.com",
    "AQR Capital Management": "aqr.com",
    "Bridgewater Associates": "bridgewater.com",
    "PDT Partners": "pdtpartners.com",
    "The Voleon Group": "voleon.com",
    "Marshall Wace": "mwam.com",
    "Brevan Howard": "brevanhoward.com",
    "Rokos Capital Management": "rokoscapital.com",
    "Capula Investment Management": "capulaglobal.com",
    "Qube Research & Technologies": "qube-rt.com",
    "G-Research": "gresearch.com",
    "GSA Capital": "gsacapital.com",
    "Systematica Investments": "systematica.com",
    "Quadrature Capital": "quadrature.ai",
    "Millennium Management": "mlp.com",
    "Balyasny Asset Management": "bamfunds.com",
    "Point72": "point72.com",
    "Cubist Systematic Strategies": "point72.com",
    "Schonfeld Strategic Advisors": "schonfeld.com",
    "Verition Fund Management": "verition.com",
    "Squarepoint Capital": "squarepoint-capital.com",
    "Dimensional Fund Advisors": "dimensional.com",
    "Acadian Asset Management": "acadian-asset.com",
    "Arrowstreet Capital": "arrowstreetcapital.com",
    "WorldQuant": "worldquant.com",
    "Renaissance Technologies": "rentec.com",
    "TGS Management": "tgsmc.com",
    "Crabel Capital Management": "crabel.com",
    "Graham Capital Management": "grahamcapital.com",
    "Quantitative Investment Management": "qimnet.com",
    "Campbell & Company": "campbell.com",
    "Goldman Sachs": "goldmansachs.com",
    "Morgan Stanley": "morganstanley.com",
    "JPMorgan Chase": "jpmorganchase.com",
    "Bank of America": "bankofamerica.com",
    "Citi": "citigroup.com",
    "Deutsche Bank": "db.com",
    "Societe Generale": "societegenerale.com",
    "BNP Paribas": "bnpparibas.com",
    "Standard Chartered": "sc.com",
    "Macquarie Group": "macquarie.com",
    "NatWest Group": "natwestgroup.com",
    "Lloyds Banking Group": "lloydsbankinggroup.com",
    "BNY": "bny.com",
    "Intercontinental Exchange": "ice.com",
    "London Stock Exchange Group": "lseg.com",
    "Hong Kong Exchanges and Clearing": "hkex.com.hk",
    "Singapore Exchange": "sgx.com",
    "Japan Exchange Group": "jpx.co.jp",
    "Options Clearing Corporation": "theocc.com",
    "National Stock Exchange of India": "nseindia.com",
    "BSE Limited": "bseindia.com",
    "Korea Exchange": "krx.co.kr",
    "KX": "kx.com",
    "Trading Technologies": "tradingtechnologies.com",
    "Interactive Brokers": "interactivebrokers.com",
    "StoneX Group": "stonex.com",
    "Quantitative Brokers": "quantitativebrokers.com",
    "Apex Fintech Solutions": "apexfintechsolutions.com",
    "SS&C Technologies": "ssctech.com",
    "S&P Global": "spglobal.com",
    "Moody's": "moodys.com",
    "Block": "block.xyz",
    "Crypto.com": "crypto.com",
    "Gate.io": "gate.io",
    "Blockchain.com": "blockchain.com",
    "Public.com": "public.com",
    "Polygon.io": "polygon.io",
    "Checkout.com": "checkout.com",
    "Copper.co": "copper.co",
    "GSR Markets": "gsr.io",
    "B2C2": "b2c2.com",
    "Wintermute": "wintermute.com",
    "Galaxy Digital": "galaxy.com",
    "Trading 212": "trading212.com",
    "interactive investor": "ii.co.uk",
    "Hargreaves Lansdown": "hl.co.uk",
    "AJ Bell": "ajbell.co.uk",
    "abrdn": "abrdn.com",
    "T. Rowe Price": "troweprice.com",
    "Dodge & Cox": "dodgeandcox.com",
    "Robert W. Baird": "rwbaird.com",
    "U.S. Bancorp": "usbank.com",
    "M&T Bank": "mtb.com",
    "Commonwealth Bank of Australia": "commbank.com.au",
    "National Australia Bank": "nab.com.au",
    "National Bank of Canada": "nbc.ca",
    "Mirae Asset Global Investments": "miraeasset.com",
    "High-Flyer Quant": "high-flyer.cn",
    "Nuvama Wealth": "nuvama.com",
    "Angel One": "angelone.in",
    "R.J. O'Brien": "rjobrien.com",
    "ED&F Man Capital": "edfmancapital.com",
    "Sea Group": "sea.com",
    "Grab Financial": "grab.com",
    "Ontario Teachers' Pension Plan": "otpp.com",
    "CPP Investments": "cppinvestments.com",
    "Norges Bank Investment Management": "nbim.no",
    "Legal & General Investment Management": "lgim.com",
    "AXA Investment Managers": "axa-im.com",
    "Allianz Global Investors": "allianzgi.com",
    "Franklin Templeton": "franklintempleton.com",
    "Trium Capital": "triumcapital.com",
    "Informed Portfolio Management": "ipm.se",
    "RPM Risk & Portfolio Management": "rpm.se",
    "Brummer & Partners": "brummer.se",
    "Lynx Asset Management": "lynxhedge.se",
}


def domain_for(name: str, slugs: list) -> str:
    if name in DOMAIN_OVERRIDES:
        return DOMAIN_OVERRIDES[name]
    base = slugs[0] if slugs else slugify(name)
    base = base.replace("_", "-").strip("-")
    return f"{base}.com" if base else ""


def main() -> None:
    firms = []
    seen = set()
    for category, rows in CATEGORIES:
        for name, regions, hints, extra in rows:
            key = name.lower()
            if key in PRUNE:
                continue
            if key in seen:
                print(f"duplicate firm skipped: {name}", file=sys.stderr)
                continue
            seen.add(key)
            slugs = slug_candidates(name, extra)
            firms.append({
                "name": name,
                "category": category,
                "regions": [r.strip() for r in regions.split(",") if r.strip()],
                "domain": domain_for(name, slugs),
                "ats": list(hints),
                "slugs": slugs,
            })

    doc = {
        "version": 1,
        "note": (
            "ats entries are HINTS probed first. The resolver validates every "
            "candidate and writes confirmed sources to data/resolved.json. "
            "Add a firm by appending a block here; leave `ats` empty to let "
            "the resolver discover it."
        ),
        "firms": firms,
    }
    yaml.safe_dump(doc, sys.stdout, sort_keys=False, allow_unicode=True, width=100)
    print(f"\n# {len(firms)} firms", file=sys.stderr)


if __name__ == "__main__":
    main()
